SELECT 
	(SELECT COUNT(*)  
	FROM covid.COVID19MEXICO2021
	WHERE REGEXP_LIKE(PAIS_ORIGEN,'[0-9]') ) AS NACIONALES,
	(SELECT COUNT(*)  
	FROM covid.COVID19MEXICO2021
	WHERE REGEXP_LIKE(PAIS_ORIGEN,'[^0-9]') ) AS EXTRANJEROS
