SELECT 
	cf.CLASIFICACION AS CLASIFICACION,
	COUNT(cm.ID_REGISTRO) AS TOTAL
FROM 
	covid.COVID19MEXICO2021 cm 
INNER JOIN 
	covid.ClasificacionFinal cf ON cf.CLAVE = cm.CLASIFICACION_FINAL 
WHERE 
	cm.CLASIFICACION_FINAL < 4
GROUP BY
	cf.CLASIFICACION WITH ROLLUP