SELECT 
	e.ENTIDAD,
	COUNT(cm.ID_REGISTRO) AS TOTAL
FROM 
	covid.COVID19MEXICO2021 AS cm 
INNER JOIN
	covid.Entidad AS e ON e.CLAVE = cm.ENTIDAD_UM 
WHERE 
	cm.FECHA_DEF != '9999-99-99'
GROUP BY
	e.ENTIDAD
ORDER BY
	TOTAL DESC